export const stations = [
  {
    id: "titan-node-omega",
    name: "Titan-Node Omega",
    tagline: "企业级低延迟大模型中转站",
    description:
      "面向生产环境的高可用 AI API 聚合入口，支持多模型自动故障切换、团队令牌管理和细粒度配额控制。",
    url: "https://openai.com/api/",
    category: "API 接入",
    tags: ["GPT-4o", "Claude", "Gemini", "企业", "低延迟"],
    models: ["GPT-4o", "Claude 3.5 Sonnet", "Gemini 1.5 Pro", "DeepSeek V3"],
    region: "US-East",
    latency: 84,
    uptime: "99.99%",
    status: "online",
    security: ["SOC2", "SAML SSO", "IP 白名单"],
    pricing: "¥0.018 / 1K tokens 起",
    launchLabel: "直达控制台",
    icon: "ServerCog",
    accent: "blue",
    featured: true,
    score: 98,
    apiShape: "OpenAI Compatible",
    useCases: ["生产 API", "团队网关", "高并发推理"],
    docs: "https://platform.openai.com/docs"
  },
  {
    id: "pulse-relay",
    name: "Pulse Relay",
    tagline: "聊天产品的高吞吐转发层",
    description:
      "专为客服、Copilot 和实时聊天应用优化，提供稳定的流式响应、请求排队和异常重试策略。",
    url: "https://www.anthropic.com/api",
    category: "聊天界面",
    tags: ["聊天", "流式", "Claude", "客服", "高吞吐"],
    models: ["Claude 3.5 Sonnet", "GPT-4o mini", "Llama 3.1"],
    region: "Singapore",
    latency: 112,
    uptime: "99.82%",
    status: "online",
    security: ["限流策略", "请求审计"],
    pricing: "¥0.009 / 1K tokens 起",
    launchLabel: "打开 Relay",
    icon: "MessagesSquare",
    accent: "cyan",
    score: 92,
    apiShape: "Chat Gateway",
    useCases: ["在线客服", "企业知识库", "多轮对话"],
    docs: "https://docs.anthropic.com/"
  },
  {
    id: "cipher-core",
    name: "Cipher Core",
    tagline: "开发测试专用模型代理",
    description:
      "面向研发团队的沙盒中转站，内置代码模型、自动测试建议、Mock API Key 和调试追踪面板。",
    url: "https://github.com/features/copilot",
    category: "开发工具",
    tags: ["代码", "调试", "Copilot", "测试", "沙盒"],
    models: ["Claude 3 Opus", "DeepSeek Coder", "Codestral", "GPT-4.1"],
    region: "Tokyo",
    latency: 98,
    uptime: "99.95%",
    status: "online",
    security: ["Secret Masking", "审计日志"],
    pricing: "¥299 / seat / 月",
    launchLabel: "进入工作台",
    icon: "Code2",
    accent: "indigo",
    score: 94,
    apiShape: "SDK + REST",
    useCases: ["代码生成", "单元测试", "CI 调试"],
    docs: "https://docs.github.com/en/copilot"
  },
  {
    id: "arch-node-x",
    name: "Arch Node X",
    tagline: "多模态与数据处理节点",
    description:
      "聚合图像、语音、OCR 与长文档处理能力，适合批量媒体工作流和数据标注平台接入。",
    url: "https://ai.google.dev/",
    category: "多模态",
    tags: ["DALL-E", "Whisper", "OCR", "图像", "批处理"],
    models: ["DALL-E 3", "Whisper V3", "Gemini 1.5 Pro Vision"],
    region: "EU-West",
    latency: 154,
    uptime: "100%",
    status: "online",
    security: ["数据隔离", "加密存储"],
    pricing: "按任务计费",
    launchLabel: "启动节点",
    icon: "DatabaseZap",
    accent: "emerald",
    score: 91,
    apiShape: "Batch API",
    useCases: ["图像生成", "语音识别", "文档解析"],
    docs: "https://ai.google.dev/docs"
  },
  {
    id: "zenith-aggregate",
    name: "Zenith Aggregate",
    tagline: "全球负载均衡 AI 路由",
    description:
      "根据地区、价格和可用性自动选择最合适的供应商，是跨境业务和多团队共用模型入口的稳定底座。",
    url: "https://openrouter.ai/",
    category: "聚合路由",
    tags: ["全模型", "路由", "成本优化", "监控", "容灾"],
    models: ["All Primary Models", "Open Models", "Vision Models"],
    region: "Global",
    latency: 42,
    uptime: "99.97%",
    status: "online",
    security: ["多租户隔离", "预算告警"],
    pricing: "按供应商透明计费",
    launchLabel: "选择路由",
    icon: "Network",
    accent: "slate",
    score: 97,
    apiShape: "Unified API",
    useCases: ["成本优化", "全球访问", "降级容灾"],
    docs: "https://openrouter.ai/docs"
  },
  {
    id: "linguist-ai",
    name: "Linguist AI",
    tagline: "实时翻译与本地化中转站",
    description:
      "统一接入多语言翻译、术语库和质量评分模型，适合出海产品、内容平台和跨境客服。",
    url: "https://www.deepl.com/pro-api",
    category: "效率工具",
    tags: ["翻译", "本地化", "术语库", "内容", "客服"],
    models: ["DeepL", "GPT-4o mini", "Qwen MT"],
    region: "Hong Kong",
    latency: 195,
    uptime: "99.9%",
    status: "degraded",
    security: ["术语权限", "内容脱敏"],
    pricing: "¥0.12 / 千字符起",
    launchLabel: "开始翻译",
    icon: "Languages",
    accent: "violet",
    score: 87,
    apiShape: "Translation API",
    useCases: ["产品出海", "文档翻译", "多语言客服"],
    docs: "https://developers.deepl.com/docs"
  },
  {
    id: "visionary-gen-v",
    name: "Visionary Gen-V",
    tagline: "图像与视频生成代理",
    description:
      "集中管理图像、短视频和风格迁移模型，提供提示词模板、任务队列和素材审核状态。",
    url: "https://replicate.com/",
    category: "多模态",
    tags: ["图像", "视频", "素材", "创意", "队列"],
    models: ["Flux", "Stable Diffusion XL", "Runway", "Kling"],
    region: "US-West",
    latency: 2450,
    uptime: "99.6%",
    status: "online",
    security: ["素材审核", "水印策略"],
    pricing: "按生成任务计费",
    launchLabel: "生成素材",
    icon: "WandSparkles",
    accent: "pink",
    score: 89,
    apiShape: "Task Queue",
    useCases: ["营销素材", "视频草图", "风格探索"],
    docs: "https://replicate.com/docs"
  },
  {
    id: "nexuscoder-pro",
    name: "NexusCoder Pro",
    tagline: "代码智能体聚合入口",
    description:
      "将代码补全、仓库问答、PR Review 和自动修复能力放在同一入口，适合工程团队统一管理 AI 开发工具。",
    url: "https://cursor.com/",
    category: "开发工具",
    tags: ["代码", "Review", "Agent", "IDE", "自动修复"],
    models: ["GPT-4.1", "Claude Sonnet", "DeepSeek Coder"],
    region: "Global",
    latency: 82,
    uptime: "99.91%",
    status: "online",
    security: ["仓库权限", "上下文隔离"],
    pricing: "¥149 / seat / 月",
    launchLabel: "打开 IDE",
    icon: "TerminalSquare",
    accent: "green",
    score: 95,
    apiShape: "Desktop + API",
    useCases: ["代码补全", "PR 审查", "问题定位"],
    docs: "https://docs.cursor.com/"
  }
];

export const categories = ["全部", ...Array.from(new Set(stations.map((station) => station.category)))];
export const allTags = Array.from(new Set(stations.flatMap((station) => station.tags))).sort((a, b) =>
  a.localeCompare(b, "zh-CN")
);
